//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BengiLED_for_C_Power.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BengiLED_for_C_Power.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Effects&gt;
        ///  &lt;Group index=&quot;0&quot; name=&quot;OpenEasy&quot;&gt;
        ///    &lt;Effect index=&quot;0&quot; name=&quot;Instant&quot; code=&quot;0&quot;/&gt;
        ///    &lt;Effect index=&quot;1&quot; name=&quot;Left&quot; code=&quot;1&quot;/&gt;
        ///    &lt;Effect index=&quot;2&quot; name=&quot;Right&quot; code=&quot;2&quot;/&gt;
        ///    &lt;Effect index=&quot;3&quot; name=&quot;Horizontal&quot; code=&quot;3&quot;/&gt;
        ///    &lt;Effect index=&quot;4&quot; name=&quot;Vertical&quot; code=&quot;4&quot;/&gt;
        ///    &lt;Effect index=&quot;5&quot; name=&quot;TopLeft&quot; code=&quot;27&quot;/&gt;
        ///    &lt;Effect index=&quot;6&quot; name=&quot;TopRight&quot; code=&quot;28&quot;/&gt;
        ///    &lt;Effect index=&quot;7&quot; name=&quot;BottomLeft&quot; code=&quot;29&quot;/&gt;
        ///    &lt;Effect index=&quot;8&quot; nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string alleffects {
            get {
                return ResourceManager.GetString("alleffects", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap American_english {
            get {
                object obj = ResourceManager.GetObject("American_english", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Language name=&quot;American_english&quot;&gt;
        ///  &lt;LocaleResource name=&quot;oldAnimationCheckBox.Text&quot; value=&quot;old animation&quot; /&gt;
        ///  &lt;LocaleResource name=&quot;send2DCheckBox.Text&quot; value=&quot;wyślij 2D&quot; /&gt;
        ///  &lt;LocaleResource name=&quot;showScreenBrightnessButton.Text&quot; value=&quot;Screen brightness&quot; /&gt;
        ///  &lt;LocaleResource name=&quot;showProgramSettingsButton.Text&quot; value=&quot;Program settings&quot; /&gt;
        ///  &lt;LocaleResource name=&quot;screenFoundInfoLabel.Text&quot; value=&quot;NOT FOUND&quot; /&gt;
        ///  &lt;LocaleResource name=&quot;playbillToolsGroupBox.T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string American_english_language_file {
            get {
                return ResourceManager.GetString("American_english_language_file", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap animation {
            get {
                object obj = ResourceManager.GetObject("animation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap animationNEW {
            get {
                object obj = ResourceManager.GetObject("animationNEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap background_img {
            get {
                object obj = ResourceManager.GetObject("background_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Belarusian {
            get {
                object obj = ResourceManager.GetObject("Belarusian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bold {
            get {
                object obj = ResourceManager.GetObject("bold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap British_english {
            get {
                object obj = ResourceManager.GetObject("British_english", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap browse {
            get {
                object obj = ResourceManager.GetObject("browse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bulgarian {
            get {
                object obj = ResourceManager.GetObject("Bulgarian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap center {
            get {
                object obj = ResourceManager.GetObject("center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chinese {
            get {
                object obj = ResourceManager.GetObject("Chinese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clock {
            get {
                object obj = ResourceManager.GetObject("clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Croatian {
            get {
                object obj = ResourceManager.GetObject("Croatian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Czech {
            get {
                object obj = ResourceManager.GetObject("Czech", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Danish {
            get {
                object obj = ResourceManager.GetObject("Danish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Estonian {
            get {
                object obj = ResourceManager.GetObject("Estonian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Finnish {
            get {
                object obj = ResourceManager.GetObject("Finnish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap French {
            get {
                object obj = ResourceManager.GetObject("French", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap German {
            get {
                object obj = ResourceManager.GetObject("German", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Greek {
            get {
                object obj = ResourceManager.GetObject("Greek", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hungarian {
            get {
                object obj = ResourceManager.GetObject("Hungarian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Italian {
            get {
                object obj = ResourceManager.GetObject("Italian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Italic {
            get {
                object obj = ResourceManager.GetObject("Italic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ItemADD {
            get {
                object obj = ResourceManager.GetObject("ItemADD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ItemDEL {
            get {
                object obj = ResourceManager.GetObject("ItemDEL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ItemDOW {
            get {
                object obj = ResourceManager.GetObject("ItemDOW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ItemUP {
            get {
                object obj = ResourceManager.GetObject("ItemUP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Latvian {
            get {
                object obj = ResourceManager.GetObject("Latvian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;LedConfiguration&gt;
        ///  &lt;Screen&gt;
        ///    &lt;Width&gt;96&lt;/Width&gt;
        ///    &lt;Height&gt;16&lt;/Height&gt;
        ///    &lt;Color&gt;1&lt;/Color&gt;
        ///  &lt;/Screen&gt;
        ///  &lt;Communication&gt;
        ///    &lt;Default&gt;
        ///      &lt;Comport&gt;COM1&lt;/Comport&gt;
        ///      &lt;Baudrate&gt;115200&lt;/Baudrate&gt;
        ///      &lt;IP&gt;192.168.1.222&lt;/IP&gt;
        ///      &lt;IPPort&gt;5200&lt;/IPPort&gt;
        ///    &lt;/Default&gt;
        ///    &lt;Current&gt;
        ///      &lt;Comport&gt;COM1&lt;/Comport&gt;
        ///      &lt;Baudrate&gt;115200&lt;/Baudrate&gt;
        ///      &lt;IP&gt;192.168.1.222&lt;/IP&gt;
        ///      &lt;IPPort&gt;5200&lt;/IPPort&gt;
        ///    &lt;/Current&gt;
        ///  &lt;/Communication&gt;
        ///  &lt;Pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ledconfig {
            get {
                return ResourceManager.GetString("ledconfig", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap left {
            get {
                object obj = ResourceManager.GetObject("left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lithuanian {
            get {
                object obj = ResourceManager.GetObject("Lithuanian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loadC {
            get {
                object obj = ResourceManager.GetObject("loadC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_atlantech {
            get {
                object obj = ResourceManager.GetObject("logo_atlantech", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_atlantech1 {
            get {
                object obj = ResourceManager.GetObject("logo_atlantech1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Norwegian {
            get {
                object obj = ResourceManager.GetObject("Norwegian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap not_known_flag {
            get {
                object obj = ResourceManager.GetObject("not_known_flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picture {
            get {
                object obj = ResourceManager.GetObject("picture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polish {
            get {
                object obj = ResourceManager.GetObject("Polish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Portuguese {
            get {
                object obj = ResourceManager.GetObject("Portuguese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap right {
            get {
                object obj = ResourceManager.GetObject("right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Romanian {
            get {
                object obj = ResourceManager.GetObject("Romanian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Russian {
            get {
                object obj = ResourceManager.GetObject("Russian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap saveC {
            get {
                object obj = ResourceManager.GetObject("saveC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Send {
            get {
                object obj = ResourceManager.GetObject("Send", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Serbian {
            get {
                object obj = ResourceManager.GetObject("Serbian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Slovak {
            get {
                object obj = ResourceManager.GetObject("Slovak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Slovene {
            get {
                object obj = ResourceManager.GetObject("Slovene", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spanish {
            get {
                object obj = ResourceManager.GetObject("Spanish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Swedish {
            get {
                object obj = ResourceManager.GetObject("Swedish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap temperature {
            get {
                object obj = ResourceManager.GetObject("temperature", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text {
            get {
                object obj = ResourceManager.GetObject("text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Turkish {
            get {
                object obj = ResourceManager.GetObject("Turkish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ukrainian {
            get {
                object obj = ResourceManager.GetObject("Ukrainian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Underline {
            get {
                object obj = ResourceManager.GetObject("Underline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoomM {
            get {
                object obj = ResourceManager.GetObject("zoomM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoomP {
            get {
                object obj = ResourceManager.GetObject("zoomP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
